# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('info', models.TextField()),
                ('author_image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Book_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_value', models.Field(choices=[('read', 'Read'), ('currently_read', 'Currently_Read'), ('wish', 'Wish')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to=b'')),
                ('published_at', models.DateField()),
                ('summary', models.TextField()),
                ('acc_rate', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('author_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Authors')),
            ],
        ),
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ManyToManyField(to='mainApp.Catergory')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followed_Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ManyToManyField(to='mainApp.Authors')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('book_id', models.ManyToManyField(to='mainApp.Books')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Book_State')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Catergory'),
        ),
    ]
