# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
